"""Analysis domain models.

This module contains entities and value objects related to
conversation analysis and scoring.
"""

import uuid
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


class Improvement(BaseModel):
    """A suggested improvement for the counseling conversation.

    Contains the issue identified, the original utterance, a suggested
    alternative, and the reasoning behind the suggestion.
    """

    issue: str = Field(description="개선이 필요한 부분")
    original: str = Field(description="실제 상담원 발화")
    suggested: str = Field(description="개선된 발화 예시")
    reason: str = Field(description="이렇게 하면 좋은 이유")
    priority: Literal["critical", "important", "nice_to_have"] = Field(
        default="important",
        description="개선 우선순위: critical(즉시 개선), important(권장), nice_to_have(선택)",
    )


class ScoreWithEvidence(BaseModel):
    """A score with supporting evidence from the conversation."""

    score: int = Field(ge=1, le=10, description="점수 (1-10)")
    evidence: str = Field(description="점수의 근거가 되는 대화 내용 인용 또는 설명")


class Scores(BaseModel):
    """Quality scores for different aspects of counseling.

    Each score ranges from 1-10, where 1 is very poor and 10 is excellent.
    """

    clarification: int = Field(ge=1, le=10, description="문제 파악")
    empathy_tone: int = Field(ge=1, le=10, description="공감/톤")
    solution_accuracy: int = Field(ge=1, le=10, description="해결 정확도")
    actionability: int = Field(ge=1, le=10, description="구체성/실행 가능성")
    confirmation_closure: int = Field(ge=1, le=10, description="확인/마무리")
    compliance_safety: int = Field(ge=1, le=10, description="리스크/정책 준수")


class ScoresWithEvidence(BaseModel):
    """Quality scores with evidence for each dimension."""

    clarification: ScoreWithEvidence = Field(description="문제 파악")
    empathy_tone: ScoreWithEvidence = Field(description="공감/톤")
    solution_accuracy: ScoreWithEvidence = Field(description="해결 정확도")
    actionability: ScoreWithEvidence = Field(description="구체성/실행 가능성")
    confirmation_closure: ScoreWithEvidence = Field(description="확인/마무리")
    compliance_safety: ScoreWithEvidence = Field(description="리스크/정책 준수")

    def to_scores(self) -> Scores:
        """Convert to simple Scores object."""
        return Scores(
            clarification=self.clarification.score,
            empathy_tone=self.empathy_tone.score,
            solution_accuracy=self.solution_accuracy.score,
            actionability=self.actionability.score,
            confirmation_closure=self.confirmation_closure.score,
            compliance_safety=self.compliance_safety.score,
        )


class FAQAccuracy(BaseModel):
    """FAQ accuracy assessment for the consultation."""

    has_faq_context: bool = Field(
        default=False, description="FAQ 컨텍스트가 제공되었는지 여부"
    )
    correct_info: list[str] = Field(
        default_factory=list,
        description="FAQ와 일치하는 정확한 정보 제공 목록",
    )
    incorrect_info: list[str] = Field(
        default_factory=list,
        description="FAQ와 다른 잘못된 정보 제공 목록 (FAQ 내용과 비교)",
    )
    missing_info: list[str] = Field(
        default_factory=list,
        description="FAQ에 있지만 상담사가 안내하지 않은 중요 정보",
    )

    @property
    def accuracy_score(self) -> float | None:
        """Calculate accuracy percentage if FAQ context was provided."""
        if not self.has_faq_context:
            return None
        total = len(self.correct_info) + len(self.incorrect_info)
        if total == 0:
            return None
        return len(self.correct_info) / total * 100


class AnalysisResult(BaseModel):
    """Complete analysis result for a counseling conversation.

    Contains scores, strengths, improvement suggestions, and overall feedback
    generated by the AI analysis.
    """

    request_id: str = Field(description="분석 요청 고유 ID")
    conversation_id: uuid.UUID | None = Field(
        default=None, description="연결된 Conversation ID"
    )
    analyzed_at: datetime = Field(description="분석 완료 시간")
    scores: Scores = Field(description="항목별 점수")
    scores_with_evidence: ScoresWithEvidence | None = Field(
        default=None, description="근거가 포함된 항목별 점수"
    )
    total_score: int = Field(ge=0, le=100, description="종합 점수 (100점 만점)")
    strengths: list[str] = Field(description="잘한 점 목록")
    improvements: list[Improvement] = Field(description="개선 사항 목록")
    overall_feedback: str = Field(description="종합적인 코칭 코멘트")
    faq_accuracy: FAQAccuracy | None = Field(
        default=None, description="FAQ 정확성 평가 (FAQ 컨텍스트 제공 시)"
    )
    is_resolved: bool | None = Field(default=None, description="상담 해결 여부")
    csat_score: int | None = Field(
        default=None, ge=1, le=5, description="고객 만족도 (1-5)"
    )

    @property
    def grade(self) -> str:
        """Return a letter grade based on total score."""
        if self.total_score >= 90:
            return "A"
        elif self.total_score >= 80:
            return "B"
        elif self.total_score >= 70:
            return "C"
        elif self.total_score >= 60:
            return "D"
        return "F"


class AnalysisHistorySummary(BaseModel):
    """Summary of an analysis result for history listing.

    Contains essential information for displaying in history lists.
    """

    request_id: str = Field(description="분석 요청 고유 ID")
    analyzed_at: datetime = Field(description="분석 완료 시간")
    total_score: int = Field(ge=0, le=100, description="종합 점수")
    grade: str = Field(description="등급 (A/B/C/D/F)")


class AnalysisFeedbackRequest(BaseModel):
    """Request for updating analysis feedback (KPIs)."""

    is_resolved: bool | None = Field(None, description="상담 해결 여부")
    csat_score: int | None = Field(None, ge=1, le=5, description="고객 만족도 (1-5)")
