"""add_kpi_fields

Revision ID: 1e902dfd16e9
Revises: a1b2c3d4e5f6
Create Date: 2026-02-01 11:57:34.632467+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1e902dfd16e9"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis_results", sa.Column("is_resolved", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "analysis_results", sa.Column("csat_score", sa.Integer(), nullable=True)
    )
    op.drop_index(op.f("ix_conversations_created_at"), table_name="conversations")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_conversations_created_at"),
        "conversations",
        ["created_at"],
        unique=False,
    )
    op.drop_column("analysis_results", "csat_score")
    op.drop_column("analysis_results", "is_resolved")
    # ### end Alembic commands ###
