"""update_rubric_schema

Revision ID: 6163adea5b37
Revises: 820ecc8dbcb5
Create Date: 2026-02-01 10:24:05.090082+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6163adea5b37"
down_revision: str | None = "820ecc8dbcb5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis_results",
        sa.Column("clarification_score", sa.Integer(), nullable=False),
    )
    op.add_column(
        "analysis_results",
        sa.Column("empathy_tone_score", sa.Integer(), nullable=False),
    )
    op.add_column(
        "analysis_results",
        sa.Column("solution_accuracy_score", sa.Integer(), nullable=False),
    )
    op.add_column(
        "analysis_results",
        sa.Column("actionability_score", sa.Integer(), nullable=False),
    )
    op.add_column(
        "analysis_results",
        sa.Column("confirmation_closure_score", sa.Integer(), nullable=False),
    )
    op.add_column(
        "analysis_results",
        sa.Column("compliance_safety_score", sa.Integer(), nullable=False),
    )
    op.drop_column("analysis_results", "understanding_score")
    op.drop_column("analysis_results", "solution_score")
    op.drop_column("analysis_results", "greeting_score")
    op.drop_column("analysis_results", "listening_score")
    op.drop_column("analysis_results", "closing_score")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "analysis_results",
        sa.Column("closing_score", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "analysis_results",
        sa.Column("listening_score", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "analysis_results",
        sa.Column("greeting_score", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "analysis_results",
        sa.Column("solution_score", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "analysis_results",
        sa.Column(
            "understanding_score", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("analysis_results", "compliance_safety_score")
    op.drop_column("analysis_results", "confirmation_closure_score")
    op.drop_column("analysis_results", "actionability_score")
    op.drop_column("analysis_results", "solution_accuracy_score")
    op.drop_column("analysis_results", "empathy_tone_score")
    op.drop_column("analysis_results", "clarification_score")
    # ### end Alembic commands ###
