"""explicit_metadata_columns

Revision ID: 4e2a78b44f48
Revises: init
Create Date: 2026-01-30 06:51:16.012523+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4e2a78b44f48"
down_revision: str | None = "init"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "faq_embeddings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("embedding", Vector(dim=1536), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("cmetadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index(op.f("ix_faq_chunks_document_id"), table_name="faq_chunks")
    op.drop_index(
        op.f("ix_faq_chunks_embedding"),
        table_name="faq_chunks",
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.drop_table("faq_chunks")
    op.drop_index(
        op.f("ix_analysis_results_analyzed_at"), table_name="analysis_results"
    )
    op.add_column("faq_documents", sa.Column("url", sa.String(), nullable=True))
    op.alter_column(
        "faq_documents", "filename", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    op.alter_column(
        "faq_documents", "file_type", existing_type=sa.VARCHAR(length=10), nullable=True
    )
    op.alter_column(
        "faq_documents", "file_size_bytes", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "faq_documents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("faq_documents", "updated_at")
    op.drop_column("faq_documents", "metadata")
    op.drop_column("faq_documents", "is_active")
    op.drop_column("faq_documents", "chunk_count")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "faq_documents",
        sa.Column(
            "chunk_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "faq_documents",
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "faq_documents",
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "faq_documents",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "faq_documents",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "faq_documents", "file_size_bytes", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "faq_documents",
        "file_type",
        existing_type=sa.VARCHAR(length=10),
        nullable=False,
    )
    op.alter_column(
        "faq_documents",
        "filename",
        existing_type=sa.VARCHAR(length=255),
        nullable=False,
    )
    op.drop_column("faq_documents", "url")
    op.create_index(
        op.f("ix_analysis_results_analyzed_at"),
        "analysis_results",
        ["analyzed_at"],
        unique=False,
    )
    op.create_table(
        "faq_chunks",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("document_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("chunk_index", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "embedding",
            Vector(dim=1536),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("token_count", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["faq_documents.id"],
            name=op.f("faq_chunks_document_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("faq_chunks_pkey")),
    )
    op.create_index(
        op.f("ix_faq_chunks_embedding"),
        "faq_chunks",
        ["embedding"],
        unique=False,
        postgresql_ops={"embedding": "vector_cosine_ops"},
        postgresql_with={"m": "16", "ef_construction": "64"},
        postgresql_using="hnsw",
    )
    op.create_index(
        op.f("ix_faq_chunks_document_id"), "faq_chunks", ["document_id"], unique=False
    )
    op.drop_table("faq_embeddings")
    # ### end Alembic commands ###
