"""add_content_to_faq_documents

Revision ID: 820ecc8dbcb5
Revises: 4e2a78b44f48
Create Date: 2026-01-30 16:03:13.800302+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "820ecc8dbcb5"
down_revision: str | None = "4e2a78b44f48"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("faq_documents", sa.Column("content", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("faq_documents", "content")
    # ### end Alembic commands ###
