"""add_is_active_to_faq_document

Revision ID: 322fada435f2
Revises: 1e902dfd16e9
Create Date: 2026-02-01 13:56:28.043081+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "322fada435f2"
down_revision: str | None = "1e902dfd16e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("faq_documents", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("faq_documents", "is_active")
    # ### end Alembic commands ###
